# resources:
#   # - ../apps/test-pod
#   - ../../certs

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: my-cluster
  namespace: flux-system
spec:
  interval: 1m
  path: .
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system