# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: test-pod
#   namespace: flux-system
# spec:
#   interval: 1m
#   path: ../apps/test-pod
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system

resources:
  - ../apps/test-pod